apiVersion: apps/v1
kind: Deployment
metadata:
  name: flask-hello-world
spec:
  replicas: 1
  selector:
    matchLabels:
      app: flask-hello-world
  template:
    metadata:
      labels:
        app: flask-hello-world
    spec:
      containers:
      - name: flask-hello-world
        image: <image_name>:<image_tag>
        ports:
        - containerPort: 5000
        env:
        - name: FLASK_APP
          value: "hello_world.py"
        - name: FLASK_ENV
          value: "development"
        volumeMounts:
        - name: code
          mountPath: /app
      volumes:
      - name: code
        configMap:
          name: code